# Generated by Django 5.0.1 on 2024-01-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodresipi', '0003_alter_resipiimage_resipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='resipi',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resipi',
            name='number_of_rating',
            field=models.IntegerField(default=0),
        ),
    ]
