# Generated by Django 5.0.1 on 2024-02-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodresipi', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resipi',
            name='avg_rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resipi',
            name='number_of_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
